fragment FilesystemFields on Filesystem {
  mountPoint
  deviceName
  type
  sizeBytes
  usedBytes
  percent
}

fragment FilesystemRowFields on Filesystem {
  ...FilesystemFields
  datasets {
    ...FilesystemFields
  }
}

fragment NetworkInterfaceFields on NetworkInterface {
  name
  receivedBytesPerSecond
  sentBytesPerSecond
}

fragment HostFields on Host {
  name
  status
  error
  history {
    sampledAt
    cpuPercent
    memoryPercent
    load1
    receivedBytesPerSecond
    sentBytesPerSecond
  }
  reading {
    sampledAt
    glancesVersion
    uptime
    system {
      hostname
      osName
      osVersion
      distribution
      description
    }
    cpu {
      totalPercent
      userPercent
      systemPercent
      iowaitPercent
      name
      coreCount
    }
    load {
      min1
      min5
      min15
    }
    memory {
      totalBytes
      usedBytes
      availableBytes
      percent
    }
    swap {
      totalBytes
      usedBytes
      percent
    }
    filesystems(detail: $detail, hideSystem: $hideSystem) {
      ...FilesystemRowFields
    }
    filesystemCount
    networkInterfaces(detail: $detail) {
      ...NetworkInterfaceFields
    }
    networkInterfaceCount
    sensors {
      label
      value
      unit
      kind
    }
    gpus {
      id
      name
      usagePercent
      memoryPercent
      temperature
      fanSpeedPercent
    }
    containers {
      name
      status
      engine
      image
      cpuPercent
      memoryBytes
    }
    processes {
      pid
      name
      user
      cpuPercent
      memoryPercent
      memoryBytes
    }
    processCount {
      total
      running
      threads
    }
  }
}

query Hosts($detail: DetailLevel!, $hideSystem: Boolean!) {
  hosts {
    ...HostFields
  }
}

query SampleInterval {
  sampleIntervalSeconds
}

query HostEverything($name: String!) {
  host(name: $name) {
    name
    reading {
      filesystems(detail: ALL) {
        ...FilesystemRowFields
      }
      networkInterfaces(detail: ALL) {
        ...NetworkInterfaceFields
      }
    }
  }
}

subscription HostChanged($intervalSeconds: Float, $detail: DetailLevel!, $hideSystem: Boolean!) {
  hostChanged(intervalSeconds: $intervalSeconds) {
    ...HostFields
  }
}
